name: news_portal
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  http: ^1.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.2
  flutter_carousel_slider:
  shared_preferences: ^2.2.2
  get: ^4.6.6
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.4
  url_launcher: ^6.3.1
  intl: ^0.20.2

flutter_native_splash:
  android_12:
    image: "assets/splash.png"
  android: true
  ios: true
  web: true
  color: "#d4e4ed"
  image: "assets/splash.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.7
  flutter_launcher_icons:

  flutter_lints: ^4.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
